spring:
  datasource:
    url: jdbc:mysql://{RDS_HOST}:3306/bukload?useSSL=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none  # 운영은 보통 Flyway 권장
