spring:
  profiles:
    active: prod  # 기본은 dev(H2)로 띄우기

server:
  port: 8081

ai:
  gemini:
    endpoint: https://generativelanguage.googleapis.com/v1
    model-region: gemini-2.5-flash
    model-courses: gemini-2.5-flash
    api-key: ${GEMINI_API_KEY}
